config:
  # MD013/line-length - Disable line length checking
  MD013: false

  # MD033/no-inline-html - Allow inline HTML for MkDocs extensions
  MD033: false

  # MD041/first-line-heading - Don't require first line to be heading
  MD041: false

  # MD024/no-duplicate-heading - Allow duplicate headings (common in docs)
  MD024:
    siblings_only: true

  # MD007/ul-indent - Indent unordered list items by 4 spaces
  MD007:
    indent: 4

globs:
  - "docs/**/*.md"
  - "*.md"
  - "!site/**"
  - "!.git/**"
