site_name: Arda Docs
site_url: https://docs.arda.xyz
theme:
  name: material
  favicon: favicon.ico
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: "snippets"
nav:
  - Home: index.md
  - Introduction:
      #   - What is Arda: introduction/what-is-arda.md # feels like a duplicate of the index page
      - Design Principles: introduction/design-principles.md
      - Architecture Overview: introduction/architecture-overview.md
      - Tokenomics: introduction/tokenomics.md
      #   - Token Models: introduction/token-models.md # duplicate of tokenomics
    #   - Token Lifecycle: introduction/token-lifecycle.md # duplicate of tokenomics
  - ArdaOS:
      - Overview: ardaos/ardaos.md
      #   - Overview: ardaos/README.md # This was originally an primitives overview doc
      - Accounting: ardaos/accounting.md
      - Compliance: ardaos/compliance.md
      - Governance: ardaos/governance.md
      - Modules: ardaos/modules.md
      - ZK TEEs: ardaos/zktees.md
      - Core Primitives: ardaos/core-primitives.md
      - Asset Primitives: ardaos/asset-primitives.md
      - Financial Primitives: ardaos/financial-primitives.md
  - Arda Core:
      - Overview: arda-core/README.md
      - Taxonomy: arda-core/taxonomy.md
      - Vault: arda-core/vault.md
      - Wallet: arda-core/wallet.md
      - Onboarding: arda-core/onboarding.md
      - Compliance: arda-core/compliance.md
      - Arda Foundry: arda-core/arda-foundry.md
      - Token Factory: arda-core/token-factory.md
      - Clear: arda-core/clear.md
      - Network-as-a-Service: arda-core/naas.md
      - Identity: arda-core/identity.md
  - Semantic Intelligence Layer:
      - Agent Primitives: semantic-intelligence-layer/agent-primitives.md
      - Identity Providers: semantic-intelligence-layer/identity-providers.md
      - Oracles: semantic-intelligence-layer/oracles.md
      - Data Residency: semantic-intelligence-layer/data-residency.md
      - External Agents: semantic-intelligence-layer/external-agents.md
  - Application Layer:
      - Arda Capital:
          - Overview: application-layer/arda-capital/README.md
          - Loan Structures: application-layer/arda-capital/loan-structures.md
          - Underwriting: application-layer/arda-capital/underwriting.md
          - Syndication: application-layer/arda-capital/syndication.md
          - Tranches: application-layer/arda-capital/tranches.md
          - Treasury: application-layer/arda-capital/treasury.md
          - Treasury Flow: application-layer/arda-capital/treasury-flow.md
          - Settlement: application-layer/arda-capital/settlement.md
          - Mandates: application-layer/arda-capital/mandates.md
          - Permissioned Pools: application-layer/arda-capital/permissioned-pools.md
          - Compliance: application-layer/arda-capital/compliance.md
          - Analytics: application-layer/arda-capital/analytics.md
      - Arda Trading:
          - Overview: application-layer/arda-trading/README.md
          - Order Book: application-layer/arda-trading/orderbook.md
          - Fractional: application-layer/arda-trading/fractional.md
          - Market Makers: application-layer/arda-trading/market-makers.md
          - Settlement: application-layer/arda-trading/settlement.md
          - Compliance: application-layer/arda-trading/compliance.md
          - Cross Chain: application-layer/arda-trading/cross-chain.md
          - Interfaces: application-layer/arda-trading/interfaces.md
  - Getting Started:
      - Interop: getting-started/interop.md
      - Fiat Onramp: getting-started/fiat-onramp.md
      - Regional Setup: getting-started/regional-deployment.md
      - Validator Setup: getting-started/validator-setup.md
      - Observability: getting-started/observability.md
      - MVP Testnet Flow: getting-started/mvp-testnet-flow.md
      - Programmable Loan: getting-started/programmable-loan.md
      - Trading RFQ Example: getting-started/trading-rfq-example.md
      - SDK:
          - Vault: getting-started/sdk/arda-vault.md
          - SDK: getting-started/sdk/sdk.md
          - Cross-Chain Infra: getting-started/sdk/cross-chain.md
          - Governance: getting-started/sdk/governance.md
  - Appendix:
      - Glossary: appendix/glossary.md
      - References: appendix/references.md
      - ERC20 Wrapping: appendix/erc20-wrapping.md
      - Bridges: appendix/bridges.md
      - Stablecoins: appendix/stablecoins.md
