site_name: Arda Docs
site_url: https://docs.arda.xyz
theme:
  name: material
  favicon: favicon.ico
nav:
  - Arda Core:
      - Overview: arda-core/README.md
      - Arda OS: arda-core/ardaos.md
      - Taxonomy: arda-core/taxonomy.md
      - Vault: arda-core/vault.md
      - Wallet: arda-core/wallet.md
      - Onboarding: arda-core/onboarding.md
      - Compliance: arda-core/compliance.md
      - Token Factory: arda-core/token-factory.md
      - Clear: arda-core/clear.md
      - Network-as-a-Service: arda-core/naas.md
      - Identity: arda-core/identity.md
      - Interop: arda-core/interop.md
  - Arda Capital:
      - Overview: arda-capital/README.md
      - Loan Structures: arda-capital/loan-structures.md
      - Underwriting: arda-capital/underwriting.md
      - Syndication: arda-capital/syndication.md
      - Tranches: arda-capital/tranches.md
      - Treasury: arda-capital/treasury.md
      - Mandates: arda-capital/mandates.md
      - Permissioned Pools: arda-capital/permissioned-pools.md
      - Compliance: arda-capital/compliance.md
      - Analytics: arda-capital/analytics.md
  - Arda Trading:
      - Overview: arda-trading/README.md
      - Order Book: arda-trading/orderbook.md
      - Fractional: arda-trading/fractional.md
      - Market Makers: arda-trading/market-makers.md
      - Settlement: arda-trading/settlement.md
      - Compliance: arda-trading/compliance.md
      - Cross Chain: arda-trading/cross-chain.md
      - Interfaces: arda-trading/interfaces.md
  - Shared Primitives:
      - Overview: shared-primitives/README.md
      - Accounting: shared-primitives/accounting.md
      - Compliance: shared-primitives/compliance.md
      - Governance: shared-primitives/governance.md
      - Modules: shared-primitives/modules.md
      - ZK TEEs: shared-primitives/zk-tees.md
  - Reference:
      - ERC20 Wrapping: reference/erc20-wrapping.md
      - Bridges: reference/bridges.md
      - Stablecoins: reference/stablecoins.md
      - External Agents: reference/external-agents.md
  - Introduction:
      - What is Arda: introduction/what-is-arda.md
      - Design Principles: introduction/design-principles.md
      - Architecture Overview: introduction/architecture-overview.md
  - Protocol:
      - Core Primitives: protocol/core-primitives.md
      - Token Models: protocol/token-models.md
      - Compliance Engine: protocol/compliance-engine.md
      - Lifecycle: protocol/lifecycle.md
      - Treasury Flow: protocol/treasury-flow.md
      - Settlement: protocol/settlement.md
  - Product Suite:
      - Arda Core: product/arda-core.md
      - Arda OS: product/arda-os.md
      - Arda Capital: product/arda-capital.md
      - Arda Trading: product/arda-trading.md
      - Arda Foundry: product/arda-foundry.md
  - Primitives:
      - Asset Primitives: primitives/asset-primitives.md
      - Financial Primitives: primitives/financial-primitives.md
      - Agent Primitives: primitives/agent-primitives.md
  - Middleware & Tools:
      - Vault: middleware/arda-vault.md
      - SDK: middleware/sdk.md
      - Cross-Chain Infra: middleware/cross-chain.md
      - Governance: middleware/governance.md
  - Deployment:
      - Regional Setup: deployment/regional-deployment.md
      - Validator Setup: deployment/validator-setup.md
      - Data Residency: deployment/data-residency.md
      - Observability: deployment/observability.md
  - Examples:
      - MVP Testnet Flow: examples/mvp-testnet-flow.md
      - Programmable Loan: examples/programmable-loan.md
      - Trading RFQ Example: examples/trading-rfq-example.md
  - Integration:
      - Fiat Onramp: integration/fiat-onramp.md
      - Identity Providers: integration/identity-providers.md
      - Oracles: integration/oracles.md
  - Appendix:
      - Glossary: appendix/glossary.md
      - References: appendix/references.md
      - Changelog: appendix/changelog.md
